PortfolioWeb/Models/Contact.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PortfolioWeb.Models
{
    public class Contact
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "필수 입력")]
        [MaxLength(30)]
        public string Name { get; set; }
        [Required(ErrorMessage = "필수 입력")]
        [MaxLength(100)]
        public string Email { get; set; }
        [Required(ErrorMessage = "필수 입력")]
        [MaxLength(1000)]
        public string Message { get; set; }
    }
}

PortfolioWeb/Models/ErrorViewModel.cs
namespace PortfolioWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PortfolioWeb/Models/PortfolioModel.cs
using System.ComponentModel.DataAnnotations;

namespace PortfolioWeb.Models
{
    public class PortfolioModel
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string? Url { get; set; }
        [FileExtensions(Extensions =".png, .jpg, .jpeg, .gif", ErrorMessage ="이미지 파일 선택")]
        public string? FileName { get; set; }
    }
}

PortfolioWeb/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace PortfolioWeb.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PortfolioWeb/Controllers/ContactController.cs
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using PortfolioWeb.Data;
using PortfolioWeb.Models;
using System.ComponentModel.DataAnnotations;

namespace PortfolioWeb.Controllers
{
    public class ContactController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ContactController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult WriteContact(Contact contact)
        {
            try
            {
                _db.Contact.Add(contact);
                _db.SaveChanges();

                Console.Write("전송 성공");
            } catch (Exception)
            {
                Console.Write("전송 실패");
            }

            return RedirectToAction("Index", "Contact");
        }
    }
}

PortfolioWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PortfolioWeb.Models;
using System.Diagnostics;

namespace PortfolioWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PortfolioWeb/Controllers/PortfolioController.cs
using Microsoft.AspNetCore.Mvc;
using PortfolioWeb.Data;

namespace PortfolioWeb.Controllers
{
    public class PortfolioController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _environment;

        public PortfolioController(ApplicationDbContext db, IWebHostEnvironment environment)
        {
            _db = db;
            _environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = _db.Portfolios.ToList();
            return View(list);
        }
    }
}

PortfolioWeb/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;

namespace PortfolioWeb.Controllers
{
    public class ResumeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PortfolioWeb/Views/Blog/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<section class="blog-section">
    <h2 class="section-title">LATEST NEWS</h2>

    <div class="blog-posts-wrapper">
        <article class="blog-post">
            <a href="#!" class="blog-post-link">
                <img src="~/images/News_1.jpg" alt="news 1" class="blog-post-thumbnail">
                <h5 class="blog-post-title">Design Conferences in 2019</h5>

            </a>
            <p class="blog-post-meta">
                <span class="post-published-date">28 DEC 2019</span>
                <a href="#!" class="post-comments">3 COMMENTS</a>
            </p>
        </article>
        <article class="blog-post">
            <a href="#!" class="blog-post-link">
                <img src="~/images/News_2.jpg" alt="news 2" class="blog-post-thumbnail">
                <h5 class="blog-post-title">Design Conferences in 2019</h5>
            </a>
            <p class="blog-post-meta">
                <span class="post-published-date">28 DEC 2019</span>
                <a href="#!" class="post-comments">3 COMMENTS</a>
            </p>
        </article>
        <article class="blog-post">
            <a href="#!" class="blog-post-link">
                <img src="~/images/News_3.jpg" alt="news 3" class="blog-post-thumbnail">
                <h5 class="blog-post-title">Design Conferences in 2019</h5>
            </a>
            <p class="blog-post-meta">
                <span class="post-published-date">28 DEC 2019</span>
                <a href="#!" class="post-comments">3 COMMENTS</a>
            </p>
        </article>
        <article class="blog-post">
            <a href="#!" class="blog-post-link">
                <img src="~/images/News_4.jpg" alt="news 4" class="blog-post-thumbnail">
                <h5 class="blog-post-title">Design Conferences in 2019</h5>
            </a>
            <p class="blog-post-meta">
                <span class="post-published-date">28 DEC 2019</span>
                <a href="#!" class="post-comments">3 COMMENTS</a>
            </p>
        </article>
        <article class="blog-post">
            <a href="#!" class="blog-post-link">
                <img src="~/images/News_5.jpg" alt="news 5" class="blog-post-thumbnail">
                <h5 class="blog-post-title">Design Conferences in 2019</h5>
            </a>
            <p class="blog-post-meta">
                <span class="post-published-date">28 DEC 2019</span>
                <a href="#!" class="post-comments">3 COMMENTS</a>
            </p>
        </article>
        <article class="blog-post">
            <a href="#!" class="blog-post-link">
                <img src="~/images/News_6.jpg" alt="news 6" class="blog-post-thumbnail">
                <h5 class="blog-post-title">Design Conferences in 2019</h5>
            </a>
            <p class="blog-post-meta">
                <span class="post-published-date">28 DEC 2019</span>
                <a href="#!" class="post-comments">3 COMMENTS</a>
            </p>
        </article>
    </div>
</section>

PortfolioWeb/Views/Contact/Index.cshtml
@model PortfolioWeb.Models.Contact

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="contact-section">
    <h2 class="section-title">GET IN TOUCH</h2>
    <p class="mb-4">아래 서식을 이용해 연락을 주시거나 기재된 연락처를 통해 연락 주세요.</p>

    <div class="contact-cards-wrapper">
        <div class="contact-card">
            <h6 class="contact-card-title">CALL ME</h6>
            <p class="contact-card-content">+82 010 9803 3487</p>
        </div>
        <div class="contact-card">
            <h6 class="contact-card-title">Email ME</h6>
            <p class="contact-card-content">fight1999club@gmail.com</p>
        </div>
    </div>

    <form asp-action="WriteContact" name="contactfrm" class="contact-form">
        <div class="form-group form-group-name">
            <label class="sr-only">Name</label>
            <input asp-for="Name" type="text" name="name" id="name" class="form-control" placeholder="NAME">
        </div>
        <div class="form-group form-group-email">
            <label class="sr-only">Email</label>
            <input asp-for="Email" type="email" name="email" id="email" class="form-control" placeholder="EMAIL">
        </div>
        <div class="form-group">
            <label class="sr-only">Message</label>
            <textarea asp-for="Message" name="message" id="message" class="form-control" placeholder="MESSAGE" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-primary form-submit-btn">SEND MESSAGE</button>
    </form>

</section>
<section class="location-section">
    <h5 class="section-title">MY LOCATION</h5>

    <div class="map-wrapper embed-responsive embed-responsive-16by9" ">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6526.019864148791!2d129.09946429502443!3d35.13142568705405!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3568ec5e8c2a819d%3A0xb48b064925bc71a5!2z67aA7IKw6rSR7Jet7IucIOuCqOq1rCDsnKDsl5Ttj4ntmZTroZw!5e0!3m2!1sko!2skr!4v1685599293574!5m2!1sko!2skr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" class="embed-responsive-item"></iframe>
    </div>
</section>

PortfolioWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<section class="intro-section">
    <h2 class="section-title">방문해주셔서 감사합니다.</h2>
    <p>
        안녕하세요. C# ASP.NET과 BootStrap을 사용해 만든 포트폴리오 사이트에 방문해주셔서 감사합니다. </br>
        해당 사이트는 포트폴리오 목적으로 만들어졌으며 MySQL을 사용해 데이터베이스를 연동했습니다. </br>
        모든 연락은 CONTACT란에 있는 폼 혹은 기재된 연락처로 해주시면 감사하겠습니다. </br>
        폼으로 작성할 경우 내부 DB에 저장됩니다.
    </p>
    <a href="#!" class="btn btn-primary btn-hire-me">HIRE ME</a>
</section>
<section class="resume-section">
    <div class="row">
        <div class="col-lg-6">
            <h6 class="section-subtitle">RESUME</h6>
            <h2 class="section-title">EDUCATION</h2>
            <ul class="time-line">
                <li class="time-line-item">
                    <span class="badge badge-primary">2016 - 2020</span>
                    <h6 class="time-line-item-title">MultiMedia Engineering</h6>
                    <p class="time-line-item-subtitle">UNIVERSITY</p>
                    <p class="time-line-item-content">
                        멀티미디어 공학과 더불어 영상 디자인 학사가 있습니다.
                    </p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2013 - 2016</span>
                    <h6 class="time-line-item-title">JungMa HighSchool</h6>
                    <p class="time-line-item-subtitle">HighSchool</p>
                    <p class="time-line-item-content">
                        전남 소재의 인문 고등학교를 졸업했습니다.
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-6">
            <h6 class="section-subtitle">RESUME</h6>
            <h2 class="section-title">Experience</h2>
            <ul class="time-line">
                <li class="time-line-item">
                    <span class="badge badge-primary">2023.01 - 2023.09</span>
                    <h6 class="time-line-item-title">IOT 시스템 개발자</h6>
                    <p class="time-line-item-subtitle">부경대학교</p>
                    <p class="time-line-item-content">
                        부경대학교에서 진행하는 IOT 시스템 개발자 수업을 진행 중입니다. </br>
                    </p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2021.06 - 2022.01</span>
                    <h6 class="time-line-item-title">AI BootCamp</h6>
                    <p class="time-line-item-subtitle">CodeStates</p>
                    <p class="time-line-item-content">
                        코드스테이츠에서 진행한 AI BootCamp를 수료했습니다.
                    </p>
                </li>
            </ul>
        </div>
    </div>
</section>
<section class="services-section">
    <h6 class="section-subtitle">WHAT I DO</h6>
    <h2 class="section-title">SERVICES</h2>
    <div class="row">
        <div class="media service-card col-lg-6">
            <div class="service-icon">
                <img src="~/images/001-target.svg" alt="target">
            </div>
            <div class="media-body">
                <h5 class="service-title">web designing</h5>
                <p class="service-description">
                    Mauris magna sapien, pharetra consectetur fringilla vitae, interdum sed
                    tortor.
                </p>
            </div>
        </div>
        <div class="media service-card col-lg-6">
            <div class="service-icon">
                <img src="~/images/003-idea.svg" alt="bulb">
            </div>
            <div class="media-body">
                <h5 class="service-title">Graphic design</h5>
                <p class="service-description">
                    Mauris magna sapien, pharetra consectetur fringilla vitae, interdum sed
                    tortor.
                </p>
            </div>
        </div>
        <div class="media service-card col-lg-6">
            <div class="service-icon">
                <img src="~/images/002-development.svg" alt="development">
            </div>
            <div class="media-body">
                <h5 class="service-title">Development</h5>
                <p class="service-description">
                    Mauris magna sapien, pharetra consectetur fringilla vitae, interdum sed
                    tortor.
                </p>
            </div>
        </div>
        <div class="media service-card col-lg-6">
            <div class="service-icon">
                <img src="~/images/004-smartphone.svg" alt="smartphone">
            </div>
            <div class="media-body">
                <h5 class="service-title">Mobile design</h5>
                <p class="service-description">
                    Mauris magna sapien, pharetra consectetur fringilla vitae, interdum sed
                    tortor.
                </p>
            </div>
        </div>
    </div>
</section>

PortfolioWeb/Views/Portfolio/Index.cshtml
@model IEnumerable<PortfolioWeb.Models.PortfolioModel>

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<section class="portfolio-section">
    <h2 class="section-title">PORTFOLIO</h2>

    <div class="portfolio-wrapper">
    @foreach (var item in Model)
    {
            <figure class="portfolio-item hover-box">
                <a href="@item.Url"><img src="~/images/@item.FileName" alt="project" class="portfolio-item-img">
                <figcaption class="portfolio-item-details overlay">
                    <h5 class="portfolio-item-title"> @item.Title </h5>
                    <p class="portfolio-item-description"> @item.Description </p>
                </figcaption>
                </a>
            </figure>
    }
    </div>
</section>

PortfolioWeb/Views/Resume/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<section class="resume-section">
    <div class="row">
        <div class="col-lg-6">
            <h6 class="section-subtitle">RESUME</h6>
            <h2 class="section-title">EDUCATION</h2>
            <ul class="time-line">
                <li class="time-line-item">
                    <span class="badge badge-primary">2016 - 2020</span>
                    <h6 class="time-line-item-title">MultiMedia Engineering</h6>
                    <p class="time-line-item-subtitle">UNIVERSITY</p>
                    <p class="time-line-item-content">
                        멀티미디어 공학과 더불어 영상 디자인 학사가 있습니다.
                    </p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2013 - 2016</span>
                    <h6 class="time-line-item-title">JungMa HighSchool</h6>
                    <p class="time-line-item-subtitle">HighSchool</p>
                    <p class="time-line-item-content">
                        전남 소재의 인문 고등학교를 졸업했습니다.
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-6">
            <h6 class="section-subtitle">RESUME</h6>
            <h2 class="section-title">STUDY</h2>
            <ul class="time-line">
                <li class="time-line-item">
                    <span class="badge badge-primary">2023.01 - 2023.09</span>
                    <h6 class="time-line-item-title">IOT 시스템 개발자</h6>
                    <p class="time-line-item-subtitle">부경대학교</p>
                    <p class="time-line-item-content">
                        부경대학교에서 진행하는 IOT 시스템 개발자 수업을 진행 중입니다. </br>
                    </p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2021.06 - 2022.01</span>
                    <h6 class="time-line-item-title">AI BootCamp</h6>
                    <p class="time-line-item-subtitle">CodeStates</p>
                    <p class="time-line-item-content">
                        코드스테이츠에서 진행한 AI BootCamp를 수료했습니다.
                    </p>
                </li>
            </ul>
        </div>
    </div>
</section>
<section class="clients-section">
    <h6 class="section-subtitle">WHAT I DO</h6>
    <h2 class="section-title">CLIENTS</h2>
    <div class="client-logos-wrapper">
        <div class="client-logo"><img src="~/images/Clients_1.svg" alt="logo" class="w-100"></div>
        <div class="client-logo"><img src="~/images/Clients_2.svg" alt="logo" class="w-100"></div>
        <div class="client-logo"><img src="~/images/Clients_3.svg" alt="logo" class="w-100"></div>
        <div class="client-logo"><img src="~/images/Clients_4.svg" alt="logo" class="w-100"></div>
    </div>
</section>
<section class="services-section">
    <h6 class="section-subtitle">WHAT I DO</h6>
    <h2 class="section-title">SERVICES</h2>
    <div class="row">
        <div class="media service-card col-lg-6">
            <div class="service-icon">
                <img src="~/images/001-target.svg" alt="target">
            </div>
            <div class="media-body">
                <h5 class="service-title">web designing</h5>
                <p class="service-description">
                    Mauris magna sapien, pharetra consectetur fringilla vitae, interdum sed
                    tortor.
                </p>
            </div>
        </div>
        <div class="media service-card col-lg-6">
            <div class="service-icon">
                <img src="~/images/003-idea.svg" alt="bulb">
            </div>
            <div class="media-body">
                <h5 class="service-title">Graphic design</h5>
                <p class="service-description">
                    Mauris magna sapien, pharetra consectetur fringilla vitae, interdum sed
                    tortor.
                </p>
            </div>
        </div>
        <div class="media service-card col-lg-6">
            <div class="service-icon">
                <img src="~/images/002-development.svg" alt="development">
            </div>
            <div class="media-body">
                <h5 class="service-title">Development</h5>
                <p class="service-description">
                    Mauris magna sapien, pharetra consectetur fringilla vitae, interdum sed
                    tortor.
                </p>
            </div>
        </div>
        <div class="media service-card col-lg-6">
            <div class="service-icon">
                <img src="~/images/004-smartphone.svg" alt="smartphone">
            </div>
            <div class="media-body">
                <h5 class="service-title">Mobile design</h5>
                <p class="service-description">
                    Mauris magna sapien, pharetra consectetur fringilla vitae, interdum sed
                    tortor.
                </p>
            </div>
        </div>
    </div>
</section>
<section class="achievements-section">
    <h6 class="section-subtitle">WHAT I DO</h6>
    <h2 class="section-title">ACHIEVEMENTS</h2>
    <div class="achievement-cards-wrapper">
        <div class="media achievement-card">
            <img src="~/images/puzzle.svg" alt="puzzle" class="achievement-card-icon">
            <div class="media-body">
                <h4 class="achievement-card-title">550+</h4>
                <p class="achievement-card-description">COMPLETED PROJECTS</p>
            </div>
        </div>
        <div class="media achievement-card">
            <img src="~/images/team.svg" alt="puzzle" class="achievement-card-icon">
            <div class="media-body">
                <h4 class="achievement-card-title">23K</h4>
                <p class="achievement-card-description">HAPPY CLIENTS</p>
            </div>
        </div>
        <div class="media achievement-card">
            <img src="~/images/trophy.svg" alt="puzzle" class="achievement-card-icon">
            <div class="media-body">
                <h4 class="achievement-card-title">55</h4>
                <p class="achievement-card-description">AWARDS RECIEVED</p>
            </div>
        </div>
    </div>
</section>

PortfolioWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PortfolioWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PortfolioWeb.styles.css" asp-append-version="true" />

    <link href="https://fonts.googleapis.com/css?family=Mukta:300,400,500,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/vendors/fortawesome/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/css/live-resume.css">

    <script>
        // nav menu active
    </script>
</head>
<body>
    <header>
        <button class="btn btn-white btn-share ml-auto mr-3 ml-md-0 mr-md-auto" onclick="copyToClipboard('https://github.com/drown-ed/');">
            <img src="~/images/share.svg" alt="share" class="btn-img">
            SHARE
        </button>
        <nav class="collapsible-nav" id="collapsible-nav">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">HOME</a>
            <a asp-area="" asp-controller="Resume" asp-action="Index" class="nav-link">RESUME</a>
            <a asp-area="" asp-controller="Portfolio" asp-action="Index" class="nav-link">PORTFOLIO</a>
            <a asp-area="" asp-controller="Blog" asp-action="Index" class="nav-link">BLOG</a>
            <a asp-area="" asp-controller="Contact" asp-action="Index" class="nav-link">CONTACT</a>
        </nav>
        <button class="btn btn-menu-toggle btn-white rounded-circle" data-toggle="collapsible-nav"
                data-target="collapsible-nav">
            <img src="~/images/hamburger.svg" alt="hamburger">
        </button>
    </header>
    <div class="content-wrapper">
        <aside>
            <div class="profile-img-wrapper">
                <img src="~/images/profile.jpg" alt="profile">
            </div>
            <h1 class="profile-name">Oh Yurina</h1>
            <div class="text-center">
                <span class="badge badge-white badge-pill profile-designation">Computer Programmer</span>
            </div>
            <nav class="social-links">
                <a href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=fight1999club@gmail.com" class="social-link"><i class="fab fa-google"></i></a>
                <a href="https://github.com/drown-ed" class="social-link"><i class="fab fa-github"></i></a>
                <a href="https://open.spotify.com/user/31xp4doechs46vpklhbjhyhje7mq?si=2ec050c993294e0c" class="social-link"><i class="fab fa-spotify"></i></a>
            </nav>
            <div class="widget">
                <h5 class="widget-title">personal information</h5>
                <div class="widget-content">
                    <p>BIRTHDAY : 13 March 1998</p>
                    <p>PHONE : +82 010 9803 3487</p>
                    <p>MAIL : fight1999club@gmail.com</p>
                </div>
            </div>
            <div class="widget card">
                <div class="card-body">
                    <div class="widget-content">
                        <h5 class="widget-title card-title">LANGUAGES</h5>
                        <p>C, C++ C#</p>
                        <p>Java, Python</p>
                    </div>
                </div>
            </div>
            <div class="widget card">
                <div class="card-body">
                    <div class="widget-content">
                        <h5 class="widget-title card-title">INTERESTS</h5>
                        <p>Book</p>
                        <p>Theatre</p>
                        <p>Video games</p>
                    </div>
                </div>
            </div>
        </aside>
        <main>
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/vendors/popperjs/core/dist/umd/popper-base.min.js"></script>
    <script src="~/vendors/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/live-resume.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>